import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * Names that exist in BOTH src/components/ui (hand-built, mockup-derived) and
 * src/components/shadcn (vendored). The vendored copies exist only so that
 * shadcn components can import each other; app code must use the WorkIt one,
 * whose variants match the designs. See docs/shadcn.md.
 */
const DUPLICATED_PRIMITIVES = ["Button", "Badge", "Card"];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/components/shadcn/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: DUPLICATED_PRIMITIVES.map((name) => ({
            name: `@/components/shadcn/${name.toLowerCase()}`,
            message: `Import { ${name} } from "@/components/ui/${name.toLowerCase()}" instead — the shadcn copy is vendored for shadcn's own internal imports and does not carry WorkIt's variants.`,
          })),
        },
      ],
    },
  },
  // Vendored shadcn source: generated, re-generated by `shadcn add`, and not
  // written to this repo's conventions. Lint it, but do not fail on style.
  {
    files: ["src/components/shadcn/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
