import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * Names that exist in both src/components/ui (hand-built, mockup-derived) and
 * src/components/shadcn (vendored), for different reasons.
 *
 * `button` is a re-export: there is one Button, and shadcn/button.tsx points at
 * it so generated components resolve. Importing the shadcn path works, but the
 * canonical path is the real one, so the rule keeps them from drifting apart in
 * the codebase.
 *
 * `badge` and `card` are not re-exports — nothing vendored needs them yet, and
 * if `shadcn add` ever writes them they will be genuinely different components
 * from ours. The rule is what stops one being imported by accident.
 *
 * See docs/shadcn.md.
 */
const DUPLICATED_PRIMITIVES = ["Button", "Badge", "Card"];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/components/shadcn/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: DUPLICATED_PRIMITIVES.map((name) => ({
            name: `@/components/shadcn/${name.toLowerCase()}`,
            message: `Import { ${name} } from "@/components/ui/${name.toLowerCase()}" instead — that is the canonical path; the shadcn one exists for shadcn's own internal imports.`,
          })),
        },
      ],
    },
  },
  // Vendored shadcn source: generated, re-generated by `shadcn add`, and not
  // written to this repo's conventions. Lint it, but do not fail on style.
  {
    files: ["src/components/shadcn/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
