import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

/**
 * Names that exist in both src/components/ui (hand-built, mockup-derived) and
 * src/components/shadcn (vendored), for different reasons.
 *
 * `button` is a re-export: there is one Button, and shadcn/button.tsx points at
 * it so generated components resolve. Importing the shadcn path works, but the
 * canonical path is the real one, so the rule keeps them from drifting apart in
 * the codebase.
 *
 * `badge` and `card` are not re-exports — nothing vendored needs them yet, and
 * if `shadcn add` ever writes them they will be genuinely different components
 * from ours. The rule is what stops one being imported by accident.
 *
 * `select` is a third shape: ui/select.tsx wraps the vendored one to change a
 * positioning default and re-exports the rest untouched. Both files therefore
 * export the same names and only one of them positions the popup the way this
 * app wants, which is exactly the drift the rule exists to catch.
 *
 * See docs/shadcn.md.
 */
const DUPLICATED_PRIMITIVES = ["Button", "Badge", "Card", "Select"];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    files: ["src/**/*.{ts,tsx}"],
    // ui/select.tsx is the one file outside shadcn/ that has to reach the
    // vendored path: it wraps that component rather than replacing it, so the
    // canonical import it points everyone else at is its own.
    ignores: [
      "src/components/shadcn/**",
      "src/components/ui/select.tsx",
      "src/db/**",
    ],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            ...DUPLICATED_PRIMITIVES.map((name) => ({
              name: `@/components/shadcn/${name.toLowerCase()}`,
              message: `Import { ${name} } from "@/components/ui/${name.toLowerCase()}" instead — that is the canonical path; the shadcn one exists for shadcn's own internal imports.`,
            })),
            {
              name: "@/db/admin",
              message:
                "dbAdmin bypasses row-level security. Use db.rls() from '@/db' instead. If you genuinely need admin access, move the code to scripts/.",
            },
          ],
        },
      ],
    },
  },
  // Vendored shadcn source: generated, re-generated by `shadcn add`, and not
  // written to this repo's conventions. Lint it, but do not fail on style.
  //
  // set-state-in-effect is off here for the same reason. It is a fair call on
  // hooks/use-mobile.ts — a media query is external state and belongs in
  // useSyncExternalStore, which is what src/app/design-kit/palette.tsx uses.
  // But that file is generated: fixing it forks it, and the next `shadcn add`
  // that touches the sidebar puts the effect back. A rule that cannot be
  // satisfied without a fork is noise on code we do not own. It stays on
  // everywhere we write hooks ourselves.
  {
    files: ["src/components/shadcn/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": "off",
      "react-hooks/set-state-in-effect": "off",
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
]);

export default eslintConfig;
