"""add auth tables

Revision ID: 0fa8dcca3a06
Revises: 
Create Date: 2026-09-18 23:05:00.266554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fa8dcca3a06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # These four ENUM types can already exist from an earlier downgrade:
    # op.drop_table() only knows the table name it's given, not its columns,
    # so a plain `op.drop_table('company_profiles')` drops the table but
    # leaves the Postgres type its `size_range` column created behind —
    # confirmed by hand against this project's own database after rolling
    # back an earlier draft of this same migration. IF EXISTS makes this a
    # no-op on a database that never had this migration applied at all.
    for enum_name in ("company_size_range", "company_role", "profile_status", "resumestatus"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_profiles',
    sa.Column('default_resume_id', sa.Uuid(), nullable=True),
    sa.Column('headline', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('other_url', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # NOT included here: the default_resume_id -> resumes.id FK. It's
    # use_alter=True on the model (app/models/profiles.py) to break the
    # circular applicant_profiles<->resumes dependency, but that flag only
    # tells SQLAlchemy's compiler to omit the constraint from CREATE TABLE —
    # nothing adds the matching ALTER unless it's issued explicitly. Verified
    # by hand against a live DB: autogenerate's original inline rendering of
    # this constraint compiles away silently, producing no FK at all. See the
    # op.create_foreign_key() call below, once `resumes` exists.
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_applicant_profiles_default_resume_id'), 'applicant_profiles', ['default_resume_id'], unique=False)
    op.create_table('company_profiles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('size_range', sa.Enum('ONE_TO_FIFTY', 'FIFTY_TO_TWO_HUNDRED', 'TWO_HUNDRED_TO_FIVE_HUNDRED', 'TOUSAND', 'FIVE_THOUSAND', 'TEN_THOUSAND', 'LARGE_THOUSAND', name='company_size_range'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_email')
    )
    op.create_table('company_memberships',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'recruiter', name='company_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'invited', 'disabled', name='profile_status'), nullable=False),
    sa.Column('headline', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_company_memberships_company_id'), 'company_memberships', ['company_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'parsed', 'parse_failed', name='resumestatus'), server_default='uploaded', nullable=False),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_applicant_id'), 'resumes', ['applicant_id'], unique=False)

    # The deferred FK from applicant_profiles, added only now that `resumes`
    # exists for it to point at. Name matches Postgres' own <table>_<column>_fkey
    # convention so it reads the same as every FK autogenerate named itself.
    op.create_foreign_key(
        'applicant_profiles_default_resume_id_fkey',
        'applicant_profiles', 'resumes',
        ['default_resume_id'], ['id'],
        ondelete='SET NULL',
    )

    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=True),
    sa.Column('company_membership_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(applicant_id IS NOT NULL) <> (company_membership_id IS NOT NULL)', name='sessions_exactly_one_account'),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_membership_id'], ['company_memberships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_applicant_id'), 'sessions', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_sessions_company_membership_id'), 'sessions', ['company_membership_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_company_membership_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_applicant_id'), table_name='sessions')
    op.drop_table('sessions')
    # Must drop before `resumes` — this FK references resumes.id, and
    # dropping a referenced table while a live FK still points at it fails.
    op.drop_constraint(
        'applicant_profiles_default_resume_id_fkey', 'applicant_profiles', type_='foreignkey'
    )
    op.drop_index(op.f('ix_resumes_applicant_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_company_memberships_company_id'), table_name='company_memberships')
    op.drop_table('company_memberships')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_applicant_profiles_default_resume_id'), table_name='applicant_profiles')
    op.drop_table('applicant_profiles')
    # ### end Alembic commands ###

    # Autogenerate's op.drop_table() calls above don't drop the ENUM types
    # the dropped columns used — see the matching note in upgrade(). Without
    # this, downgrading this migration reproduces the exact "type already
    # exists" failure this migration's own upgrade() has to guard against.
    for enum_name in ("company_size_range", "company_role", "profile_status", "resumestatus"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
