"""tie account ids to supabase auth.users, drop password_hash

Revision ID: 197cfcdecdb8
Revises: b740d8d00619
Create Date: 2026-09-24 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '197cfcdecdb8'
down_revision: Union[str, Sequence[str], None] = 'b740d8d00619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

ACCOUNT_TABLES = ('applicant_profiles', 'company_memberships')


def upgrade() -> None:
    """Upgrade schema.

    Hand-written, not autogenerated: the foreign key points into Supabase's
    `auth` schema, which env.py deliberately keeps autogenerate away from.
    """
    # Accounts made under the old FastAPI auth have ids Supabase has never
    # heard of, so the foreign keys below would fail on them with a bare
    # constraint error. Stop first with one that says what to do. Deleting
    # them here instead would be a silent data loss in a schema migration.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM applicant_profiles p
                WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = p.id)
            ) OR EXISTS (
                SELECT 1 FROM company_memberships m
                WHERE NOT EXISTS (SELECT 1 FROM auth.users u WHERE u.id = m.id)
            ) THEN
                RAISE EXCEPTION 'Account rows exist with no matching auth.users row. '
                    'They were created by the old password auth and cannot sign in under '
                    'Supabase Auth. Delete them (or create matching auth users) and re-run.';
            END IF;
        END $$;
        """
    )

    for table in ACCOUNT_TABLES:
        op.drop_column(table, 'password_hash')
        # The id now comes from auth.users; a generated one would name no user.
        op.alter_column(table, 'id', server_default=None)
        op.create_foreign_key(
            f'{table}_id_fkey',
            table,
            'users',
            ['id'],
            ['id'],
            referent_schema='auth',
            ondelete='CASCADE',
        )


def downgrade() -> None:
    """Downgrade schema.

    password_hash comes back NULLABLE, unlike the NOT NULL column b740d8d00619
    created: rows made under Supabase Auth have no hash to restore, and those
    accounts cannot sign in under the old auth whichever way this goes.
    """
    for table in ACCOUNT_TABLES:
        op.drop_constraint(f'{table}_id_fkey', table, type_='foreignkey')
        op.alter_column(table, 'id', server_default=sa.text('gen_random_uuid()'))
        op.add_column(table, sa.Column('password_hash', sa.String(length=255), nullable=True))
