"""seed international states

Revision ID: 60e294868d57
Revises: 2d9b0e7c41c2
Create Date: 2026-09-22 13:08:46.830375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e294868d57'
down_revision: Union[str, Sequence[str], None] = '2d9b0e7c41c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Frozen top-level ISO 3166-2 subdivisions, generated from pycountry
# 26.2.16, for the countries US job boards most often list.
#
# Top level only: "London, England, United Kingdom" names England, not a
# borough, and states is one level deep. Entries that are ISO countries in
# their own right (Hong Kong, Taiwan, Aruba, French overseas territories) are
# left out; they already have a row in countries.
#
# Names are English where ISO gives the local one ("Bavaria", not "Bayern");
# the local names belong to the location resolver as aliases. See
# app/models/CLAUDE.md.
# Ireland, Singapore and Poland are left country-only: their top level
# (provinces, districts, voivodeships) is not what postings write.
STATES = [
    # CA
    ('CA-AB', 'CA', 'Alberta'),
    ('CA-BC', 'CA', 'British Columbia'),
    ('CA-MB', 'CA', 'Manitoba'),
    ('CA-NB', 'CA', 'New Brunswick'),
    ('CA-NL', 'CA', 'Newfoundland and Labrador'),
    ('CA-NS', 'CA', 'Nova Scotia'),
    ('CA-NT', 'CA', 'Northwest Territories'),
    ('CA-NU', 'CA', 'Nunavut'),
    ('CA-ON', 'CA', 'Ontario'),
    ('CA-PE', 'CA', 'Prince Edward Island'),
    ('CA-QC', 'CA', 'Quebec'),
    ('CA-SK', 'CA', 'Saskatchewan'),
    ('CA-YT', 'CA', 'Yukon'),
    # GB
    ('GB-ENG', 'GB', 'England'),
    ('GB-NIR', 'GB', 'Northern Ireland'),
    ('GB-SCT', 'GB', 'Scotland'),
    ('GB-WLS', 'GB', 'Wales'),
    # DE
    ('DE-BB', 'DE', 'Brandenburg'),
    ('DE-BE', 'DE', 'Berlin'),
    ('DE-BW', 'DE', 'Baden-Württemberg'),
    ('DE-BY', 'DE', 'Bavaria'),
    ('DE-HB', 'DE', 'Bremen'),
    ('DE-HE', 'DE', 'Hesse'),
    ('DE-HH', 'DE', 'Hamburg'),
    ('DE-MV', 'DE', 'Mecklenburg-Western Pomerania'),
    ('DE-NI', 'DE', 'Lower Saxony'),
    ('DE-NW', 'DE', 'North Rhine-Westphalia'),
    ('DE-RP', 'DE', 'Rhineland-Palatinate'),
    ('DE-SH', 'DE', 'Schleswig-Holstein'),
    ('DE-SL', 'DE', 'Saarland'),
    ('DE-SN', 'DE', 'Saxony'),
    ('DE-ST', 'DE', 'Saxony-Anhalt'),
    ('DE-TH', 'DE', 'Thuringia'),
    # FR
    ('FR-20R', 'FR', 'Corsica'),
    ('FR-ARA', 'FR', 'Auvergne-Rhône-Alpes'),
    ('FR-BFC', 'FR', 'Bourgogne-Franche-Comté'),
    ('FR-BRE', 'FR', 'Brittany'),
    ('FR-CVL', 'FR', 'Centre-Val de Loire'),
    ('FR-GES', 'FR', 'Grand Est'),
    ('FR-HDF', 'FR', 'Hauts-de-France'),
    ('FR-IDF', 'FR', 'Île-de-France'),
    ('FR-NAQ', 'FR', 'Nouvelle-Aquitaine'),
    ('FR-NOR', 'FR', 'Normandy'),
    ('FR-OCC', 'FR', 'Occitanie'),
    ('FR-PAC', 'FR', "Provence-Alpes-Côte d'Azur"),
    ('FR-PDL', 'FR', 'Pays de la Loire'),
    # NL
    ('NL-DR', 'NL', 'Drenthe'),
    ('NL-FL', 'NL', 'Flevoland'),
    ('NL-FR', 'NL', 'Friesland'),
    ('NL-GE', 'NL', 'Gelderland'),
    ('NL-GR', 'NL', 'Groningen'),
    ('NL-LI', 'NL', 'Limburg'),
    ('NL-NB', 'NL', 'North Brabant'),
    ('NL-NH', 'NL', 'North Holland'),
    ('NL-OV', 'NL', 'Overijssel'),
    ('NL-UT', 'NL', 'Utrecht'),
    ('NL-ZE', 'NL', 'Zeeland'),
    ('NL-ZH', 'NL', 'South Holland'),
    # ES
    ('ES-AN', 'ES', 'Andalusia'),
    ('ES-AR', 'ES', 'Aragon'),
    ('ES-AS', 'ES', 'Asturias'),
    ('ES-CB', 'ES', 'Cantabria'),
    ('ES-CE', 'ES', 'Ceuta'),
    ('ES-CL', 'ES', 'Castile and León'),
    ('ES-CM', 'ES', 'Castilla-La Mancha'),
    ('ES-CN', 'ES', 'Canary Islands'),
    ('ES-CT', 'ES', 'Catalonia'),
    ('ES-EX', 'ES', 'Extremadura'),
    ('ES-GA', 'ES', 'Galicia'),
    ('ES-IB', 'ES', 'Balearic Islands'),
    ('ES-MC', 'ES', 'Region of Murcia'),
    ('ES-MD', 'ES', 'Community of Madrid'),
    ('ES-ML', 'ES', 'Melilla'),
    ('ES-NC', 'ES', 'Navarre'),
    ('ES-PV', 'ES', 'Basque Country'),
    ('ES-RI', 'ES', 'La Rioja'),
    ('ES-VC', 'ES', 'Valencian Community'),
    # IT
    ('IT-21', 'IT', 'Piedmont'),
    ('IT-23', 'IT', 'Aosta Valley'),
    ('IT-25', 'IT', 'Lombardy'),
    ('IT-32', 'IT', 'Trentino-South Tyrol'),
    ('IT-34', 'IT', 'Veneto'),
    ('IT-36', 'IT', 'Friuli-Venezia Giulia'),
    ('IT-42', 'IT', 'Liguria'),
    ('IT-45', 'IT', 'Emilia-Romagna'),
    ('IT-52', 'IT', 'Tuscany'),
    ('IT-55', 'IT', 'Umbria'),
    ('IT-57', 'IT', 'Marche'),
    ('IT-62', 'IT', 'Lazio'),
    ('IT-65', 'IT', 'Abruzzo'),
    ('IT-67', 'IT', 'Molise'),
    ('IT-72', 'IT', 'Campania'),
    ('IT-75', 'IT', 'Apulia'),
    ('IT-77', 'IT', 'Basilicata'),
    ('IT-78', 'IT', 'Calabria'),
    ('IT-82', 'IT', 'Sicily'),
    ('IT-88', 'IT', 'Sardinia'),
    # CH
    ('CH-AG', 'CH', 'Aargau'),
    ('CH-AI', 'CH', 'Appenzell Innerrhoden'),
    ('CH-AR', 'CH', 'Appenzell Ausserrhoden'),
    ('CH-BE', 'CH', 'Bern'),
    ('CH-BL', 'CH', 'Basel-Landschaft'),
    ('CH-BS', 'CH', 'Basel-Stadt'),
    ('CH-FR', 'CH', 'Fribourg'),
    ('CH-GE', 'CH', 'Geneva'),
    ('CH-GL', 'CH', 'Glarus'),
    ('CH-GR', 'CH', 'Grisons'),
    ('CH-JU', 'CH', 'Jura'),
    ('CH-LU', 'CH', 'Lucerne'),
    ('CH-NE', 'CH', 'Neuchâtel'),
    ('CH-NW', 'CH', 'Nidwalden'),
    ('CH-OW', 'CH', 'Obwalden'),
    ('CH-SG', 'CH', 'St. Gallen'),
    ('CH-SH', 'CH', 'Schaffhausen'),
    ('CH-SO', 'CH', 'Solothurn'),
    ('CH-SZ', 'CH', 'Schwyz'),
    ('CH-TG', 'CH', 'Thurgau'),
    ('CH-TI', 'CH', 'Ticino'),
    ('CH-UR', 'CH', 'Uri'),
    ('CH-VD', 'CH', 'Vaud'),
    ('CH-VS', 'CH', 'Valais'),
    ('CH-ZG', 'CH', 'Zug'),
    ('CH-ZH', 'CH', 'Zurich'),
    # IN
    ('IN-AN', 'IN', 'Andaman and Nicobar Islands'),
    ('IN-AP', 'IN', 'Andhra Pradesh'),
    ('IN-AR', 'IN', 'Arunachal Pradesh'),
    ('IN-AS', 'IN', 'Assam'),
    ('IN-BR', 'IN', 'Bihar'),
    ('IN-CG', 'IN', 'Chhattisgarh'),
    ('IN-CH', 'IN', 'Chandigarh'),
    ('IN-DH', 'IN', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('IN-DL', 'IN', 'Delhi'),
    ('IN-GA', 'IN', 'Goa'),
    ('IN-GJ', 'IN', 'Gujarat'),
    ('IN-HP', 'IN', 'Himachal Pradesh'),
    ('IN-HR', 'IN', 'Haryana'),
    ('IN-JH', 'IN', 'Jharkhand'),
    ('IN-JK', 'IN', 'Jammu and Kashmir'),
    ('IN-KA', 'IN', 'Karnataka'),
    ('IN-KL', 'IN', 'Kerala'),
    ('IN-LA', 'IN', 'Ladakh'),
    ('IN-LD', 'IN', 'Lakshadweep'),
    ('IN-MH', 'IN', 'Maharashtra'),
    ('IN-ML', 'IN', 'Meghalaya'),
    ('IN-MN', 'IN', 'Manipur'),
    ('IN-MP', 'IN', 'Madhya Pradesh'),
    ('IN-MZ', 'IN', 'Mizoram'),
    ('IN-NL', 'IN', 'Nagaland'),
    ('IN-OD', 'IN', 'Odisha'),
    ('IN-PB', 'IN', 'Punjab'),
    ('IN-PY', 'IN', 'Puducherry'),
    ('IN-RJ', 'IN', 'Rajasthan'),
    ('IN-SK', 'IN', 'Sikkim'),
    ('IN-TN', 'IN', 'Tamil Nadu'),
    ('IN-TR', 'IN', 'Tripura'),
    ('IN-TS', 'IN', 'Telangana'),
    ('IN-UK', 'IN', 'Uttarakhand'),
    ('IN-UP', 'IN', 'Uttar Pradesh'),
    ('IN-WB', 'IN', 'West Bengal'),
    # AU
    ('AU-ACT', 'AU', 'Australian Capital Territory'),
    ('AU-NSW', 'AU', 'New South Wales'),
    ('AU-NT', 'AU', 'Northern Territory'),
    ('AU-QLD', 'AU', 'Queensland'),
    ('AU-SA', 'AU', 'South Australia'),
    ('AU-TAS', 'AU', 'Tasmania'),
    ('AU-VIC', 'AU', 'Victoria'),
    ('AU-WA', 'AU', 'Western Australia'),
    # MX
    ('MX-AGU', 'MX', 'Aguascalientes'),
    ('MX-BCN', 'MX', 'Baja California'),
    ('MX-BCS', 'MX', 'Baja California Sur'),
    ('MX-CAM', 'MX', 'Campeche'),
    ('MX-CHH', 'MX', 'Chihuahua'),
    ('MX-CHP', 'MX', 'Chiapas'),
    ('MX-CMX', 'MX', 'Mexico City'),
    ('MX-COA', 'MX', 'Coahuila'),
    ('MX-COL', 'MX', 'Colima'),
    ('MX-DUR', 'MX', 'Durango'),
    ('MX-GRO', 'MX', 'Guerrero'),
    ('MX-GUA', 'MX', 'Guanajuato'),
    ('MX-HID', 'MX', 'Hidalgo'),
    ('MX-JAL', 'MX', 'Jalisco'),
    ('MX-MEX', 'MX', 'State of Mexico'),
    ('MX-MIC', 'MX', 'Michoacán'),
    ('MX-MOR', 'MX', 'Morelos'),
    ('MX-NAY', 'MX', 'Nayarit'),
    ('MX-NLE', 'MX', 'Nuevo León'),
    ('MX-OAX', 'MX', 'Oaxaca'),
    ('MX-PUE', 'MX', 'Puebla'),
    ('MX-QUE', 'MX', 'Querétaro'),
    ('MX-ROO', 'MX', 'Quintana Roo'),
    ('MX-SIN', 'MX', 'Sinaloa'),
    ('MX-SLP', 'MX', 'San Luis Potosí'),
    ('MX-SON', 'MX', 'Sonora'),
    ('MX-TAB', 'MX', 'Tabasco'),
    ('MX-TAM', 'MX', 'Tamaulipas'),
    ('MX-TLA', 'MX', 'Tlaxcala'),
    ('MX-VER', 'MX', 'Veracruz'),
    ('MX-YUC', 'MX', 'Yucatán'),
    ('MX-ZAC', 'MX', 'Zacatecas'),
    # BR
    ('BR-AC', 'BR', 'Acre'),
    ('BR-AL', 'BR', 'Alagoas'),
    ('BR-AM', 'BR', 'Amazonas'),
    ('BR-AP', 'BR', 'Amapá'),
    ('BR-BA', 'BR', 'Bahia'),
    ('BR-CE', 'BR', 'Ceará'),
    ('BR-DF', 'BR', 'Distrito Federal'),
    ('BR-ES', 'BR', 'Espírito Santo'),
    ('BR-GO', 'BR', 'Goiás'),
    ('BR-MA', 'BR', 'Maranhão'),
    ('BR-MG', 'BR', 'Minas Gerais'),
    ('BR-MS', 'BR', 'Mato Grosso do Sul'),
    ('BR-MT', 'BR', 'Mato Grosso'),
    ('BR-PA', 'BR', 'Pará'),
    ('BR-PB', 'BR', 'Paraíba'),
    ('BR-PE', 'BR', 'Pernambuco'),
    ('BR-PI', 'BR', 'Piauí'),
    ('BR-PR', 'BR', 'Paraná'),
    ('BR-RJ', 'BR', 'Rio de Janeiro'),
    ('BR-RN', 'BR', 'Rio Grande do Norte'),
    ('BR-RO', 'BR', 'Rondônia'),
    ('BR-RR', 'BR', 'Roraima'),
    ('BR-RS', 'BR', 'Rio Grande do Sul'),
    ('BR-SC', 'BR', 'Santa Catarina'),
    ('BR-SE', 'BR', 'Sergipe'),
    ('BR-SP', 'BR', 'São Paulo'),
    ('BR-TO', 'BR', 'Tocantins'),
    # JP
    ('JP-01', 'JP', 'Hokkaido'),
    ('JP-02', 'JP', 'Aomori'),
    ('JP-03', 'JP', 'Iwate'),
    ('JP-04', 'JP', 'Miyagi'),
    ('JP-05', 'JP', 'Akita'),
    ('JP-06', 'JP', 'Yamagata'),
    ('JP-07', 'JP', 'Fukushima'),
    ('JP-08', 'JP', 'Ibaraki'),
    ('JP-09', 'JP', 'Tochigi'),
    ('JP-10', 'JP', 'Gunma'),
    ('JP-11', 'JP', 'Saitama'),
    ('JP-12', 'JP', 'Chiba'),
    ('JP-13', 'JP', 'Tokyo'),
    ('JP-14', 'JP', 'Kanagawa'),
    ('JP-15', 'JP', 'Niigata'),
    ('JP-16', 'JP', 'Toyama'),
    ('JP-17', 'JP', 'Ishikawa'),
    ('JP-18', 'JP', 'Fukui'),
    ('JP-19', 'JP', 'Yamanashi'),
    ('JP-20', 'JP', 'Nagano'),
    ('JP-21', 'JP', 'Gifu'),
    ('JP-22', 'JP', 'Shizuoka'),
    ('JP-23', 'JP', 'Aichi'),
    ('JP-24', 'JP', 'Mie'),
    ('JP-25', 'JP', 'Shiga'),
    ('JP-26', 'JP', 'Kyoto'),
    ('JP-27', 'JP', 'Osaka'),
    ('JP-28', 'JP', 'Hyogo'),
    ('JP-29', 'JP', 'Nara'),
    ('JP-30', 'JP', 'Wakayama'),
    ('JP-31', 'JP', 'Tottori'),
    ('JP-32', 'JP', 'Shimane'),
    ('JP-33', 'JP', 'Okayama'),
    ('JP-34', 'JP', 'Hiroshima'),
    ('JP-35', 'JP', 'Yamaguchi'),
    ('JP-36', 'JP', 'Tokushima'),
    ('JP-37', 'JP', 'Kagawa'),
    ('JP-38', 'JP', 'Ehime'),
    ('JP-39', 'JP', 'Kochi'),
    ('JP-40', 'JP', 'Fukuoka'),
    ('JP-41', 'JP', 'Saga'),
    ('JP-42', 'JP', 'Nagasaki'),
    ('JP-43', 'JP', 'Kumamoto'),
    ('JP-44', 'JP', 'Oita'),
    ('JP-45', 'JP', 'Miyazaki'),
    ('JP-46', 'JP', 'Kagoshima'),
    ('JP-47', 'JP', 'Okinawa'),
    # CN
    ('CN-AH', 'CN', 'Anhui'),
    ('CN-BJ', 'CN', 'Beijing'),
    ('CN-CQ', 'CN', 'Chongqing'),
    ('CN-FJ', 'CN', 'Fujian'),
    ('CN-GD', 'CN', 'Guangdong'),
    ('CN-GS', 'CN', 'Gansu'),
    ('CN-GX', 'CN', 'Guangxi'),
    ('CN-GZ', 'CN', 'Guizhou'),
    ('CN-HA', 'CN', 'Henan'),
    ('CN-HB', 'CN', 'Hubei'),
    ('CN-HE', 'CN', 'Hebei'),
    ('CN-HI', 'CN', 'Hainan'),
    ('CN-HL', 'CN', 'Heilongjiang'),
    ('CN-HN', 'CN', 'Hunan'),
    ('CN-JL', 'CN', 'Jilin'),
    ('CN-JS', 'CN', 'Jiangsu'),
    ('CN-JX', 'CN', 'Jiangxi'),
    ('CN-LN', 'CN', 'Liaoning'),
    ('CN-NM', 'CN', 'Inner Mongolia'),
    ('CN-NX', 'CN', 'Ningxia'),
    ('CN-QH', 'CN', 'Qinghai'),
    ('CN-SC', 'CN', 'Sichuan'),
    ('CN-SD', 'CN', 'Shandong'),
    ('CN-SH', 'CN', 'Shanghai'),
    ('CN-SN', 'CN', 'Shaanxi'),
    ('CN-SX', 'CN', 'Shanxi'),
    ('CN-TJ', 'CN', 'Tianjin'),
    ('CN-XJ', 'CN', 'Xinjiang'),
    ('CN-XZ', 'CN', 'Tibet'),
    ('CN-YN', 'CN', 'Yunnan'),
    ('CN-ZJ', 'CN', 'Zhejiang'),
    # IL
    ('IL-D', 'IL', 'Southern District'),
    ('IL-HA', 'IL', 'Haifa District'),
    ('IL-JM', 'IL', 'Jerusalem District'),
    ('IL-M', 'IL', 'Central District'),
    ('IL-TA', 'IL', 'Tel Aviv District'),
    ('IL-Z', 'IL', 'Northern District'),
]

states = sa.table(
    "states",
    sa.column("code", sa.String(6)),
    sa.column("country_code", sa.CHAR(2)),
    sa.column("name", sa.Text),
)


def upgrade() -> None:
    """Upgrade schema."""
    op.bulk_insert(
        states,
        [{"code": c, "country_code": cc, "name": n} for c, cc, n in STATES],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(states.delete().where(states.c.code.in_([c for c, _, _ in STATES])))
