"""initial schema

Revision ID: dee263a84adb
Revises: 
Create Date: 2026-09-21 18:06:34.099255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dee263a84adb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant_profiles',
    sa.Column('default_resume_id', sa.Uuid(), nullable=True),
    sa.Column('headline', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('portfolio_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('other_url', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_resume_id'], ['resumes.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_applicant_profiles_default_resume_id'), 'applicant_profiles', ['default_resume_id'], unique=False)
    op.create_table('company_profiles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('size_range', sa.Enum('ONE_TO_FIFTY', 'FIFTY_TO_TWO_HUNDRED', 'TWO_HUNDRED_TO_FIVE_HUNDRED', 'TOUSAND', 'FIVE_THOUSAND', 'TEN_THOUSAND', 'LARGE_THOUSAND', name='company_size_range'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_email')
    )
    op.create_table('countries',
    sa.Column('code', sa.CHAR(length=2), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('company_memberships',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'recruiter', name='company_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'invited', 'disabled', name='profile_status'), nullable=False),
    sa.Column('headline', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_company_memberships_company_id'), 'company_memberships', ['company_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('applicant_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'parsed', 'parse_failed', name='resumestatus'), server_default='uploaded', nullable=False),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicant_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_applicant_id'), 'resumes', ['applicant_id'], unique=False)
    op.create_table('states',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('country_code', sa.CHAR(length=2), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['country_code'], ['countries.code'], ),
    sa.PrimaryKeyConstraint('code'),
    sa.UniqueConstraint('code', 'country_code')
    )
    op.create_index(op.f('ix_states_country_code'), 'states', ['country_code'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('posted_by_recruiter_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('job_type', sa.Enum('full_time', 'part_time', 'contract', name='job_type'), nullable=False),
    sa.Column('experience_level', sa.Enum('internship', 'new_grad', 'other', name='experience_level'), nullable=False),
    sa.Column('min_years_experience', sa.SmallInteger(), nullable=True),
    sa.Column('work_style', sa.Enum('remote', 'hybrid', 'onsite', name='work_style'), nullable=False),
    sa.Column('location_state', sa.String(), nullable=False),
    sa.Column('location_country', sa.String(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.CHAR(length=3), server_default='USD', nullable=False),
    sa.Column('salary_period', sa.Enum('year', 'hour', name='salary_period'), server_default='year', nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'closed', name='job_post_status'), server_default='draft', nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('location_state IS NULL OR location_country IS NOT NULL', name='state_requires_country'),
    sa.CheckConstraint('salary IS NOT NULL OR (salary_min IS NOT NULL AND salary_max IS NOT NULL)', name='salary_exist'),
    sa.CheckConstraint('salary_min >= 0 AND salary_max >= 0 AND salary >= 0', name='salary_non_negative'),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max', name='salary_range_ordered'),
    sa.ForeignKeyConstraint(['company_id'], ['company_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_state', 'location_country'], ['states.code', 'states.country_code'], name='country_state_reference_exist'),
    sa.ForeignKeyConstraint(['posted_by_recruiter_id'], ['company_memberships.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_company_id'), 'job_postings', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_postings_posted_by_recruiter_id'), 'job_postings', ['posted_by_recruiter_id'], unique=False)
    op.create_index('job_postings_status_idx', 'job_postings', ['status', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###

    # applicant_profiles and resumes reference each other, so this FK cannot be
    # inlined into either CREATE TABLE. The model marks it use_alter=True, which
    # makes SQLAlchemy omit it from CREATE TABLE — but autogenerate does not then
    # emit the ALTER that adds it back, so without this the constraint silently
    # never exists. Verified against `alembic upgrade head --sql`: zero ALTER
    # TABLE statements were generated.
    op.create_foreign_key(
        'fk_applicant_profiles_default_resume_id',
        'applicant_profiles', 'resumes',
        ['default_resume_id'], ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Must come first: while this FK exists, dropping `resumes` below fails
    # because applicant_profiles still references it.
    op.drop_constraint(
        'fk_applicant_profiles_default_resume_id',
        'applicant_profiles',
        type_='foreignkey',
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('job_postings_status_idx', table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_posted_by_recruiter_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_company_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_states_country_code'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_resumes_applicant_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_company_memberships_company_id'), table_name='company_memberships')
    op.drop_table('company_memberships')
    op.drop_table('countries')
    op.drop_table('company_profiles')
    op.drop_index(op.f('ix_applicant_profiles_default_resume_id'), table_name='applicant_profiles')
    op.drop_table('applicant_profiles')
    # ### end Alembic commands ###
